name = "Rust Project"
description = "Meetings for all of the teams in the Rust project"

[meta]
includes = [
  "compiler.toml",
  "council.toml",
  "dev-tools.toml",
  "infra.toml",
  "lang.toml",
  "libs.toml",
  "spec.toml",
  "wg-binary-size.toml",
  "wg-embedded.toml",
]
